#!/bin/zsh

compile_and_load () {
  local file="$1"
  shift

  # Assume no compiled library exists
  local compile=1

  [[ -f "$file" ]] && {
    # Compiled file exists, maybe no recompilation
    compile=0

    # Unless one of the files in library have been updated
    for f in "$@"; do
      [[ "$file" -nt "$ZDOTDIR/functions/$f" ]] && { compile=1; break; }
    done
  }

  # Prepend compiled rc functions to fpath
  fpath=("$file" "$fpath[@]")

  # Autoload functions (either from already compiled word code or from source
  # (to be compiled))
  autoload -URz ${@[@]:t}

  # (Maybe) compile library (as memory mapped file, to facilitate reuse)
  (( $compile )) && zcompile -UMaz "$file" ${@[@]:t}
    #zcompile -UMaz "$file" $ZDOTDIR/functions/{"${(j.,.)@[@]}"}
}

compile_and_load "$@"

# vim: ft=zsh et tw=78 ts=2 sts=2 sw=2 cc=80 fdm=marker
