#!/bin/zsh

fpath=($ZDOTDIR/env_funcs_cache.zwc "$fpath[@]")

() {
  [[ -f "$ZDOTDIR/env_funcs_cache.zwc" ]] || return 0
  for f in ${env_funcs[@]}; do
    [[ "$f" -nt $ZDOTDIR/env_funcs_cache.zwc ]] && return 0
  done
  return 1
} && {
    autoload -URzm ${env_funcs[@]:t}
    zcompile -UMaz $ZDOTDIR/env_funcs_cache.zwc "${(ps: :)env_funcs[@]:t}"
  } || autoload -URz ${env_funcs[@]:t}

# vim: ft=zsh et tw=78 ts=2 sts=2 sw=2 cc=80 fdm=marker
