#!/bin/zsh

zmodload zsh/mapfile

# Process a given file line-by-line with a given command.
# Takes two arguments:
#   filename, name of command to use in processing
#
# Passed-in command is given three arguments:
#   total number of lines, current line number, current line contents
function read_file () {
  local fname="$1"
  local cmd="$2"

  local lines=( "${(@f)mapfile[$FNAME]}" )
  local integer length=$#lines
  local integer l_no=1

  for l in "${lines[@]}"; do
    eval "$cmd $length $l_no $l"
    (( l_no++ ))
  done
}

read_file "$@"

# vim: ft=zsh et tw=78 ts=2 sts=2 sw=2 cc=80
