#!/bin/zsh

# Determine if any component of a given path is a symbolic link
function path_contains_symlink () {
  local current=$PWD
  while [[ $PWD -ne "/" ]]; do
    [[ -h "$current:t" ]] && return true
    current="$current:h"
  done
  return false
}

path_contains_symlink "$@"

# vim: ft=zsh et tw=78 ts=2 sts=2 sw=2 cc=80
