#!/bin/zsh
# From:
# http://zsh.sourceforge.net/Contrib/startup/users/debbiep/dot.zshenv
#
# Will rationalise a path array (as in fpath/path/manpath etc) to include
# folders only once. Returns boolean value based on success status.
## TODO find out if this is (still?) needed
rationalize_path () {
  # Note that this works only on arrays, not colon-delimited strings.
  local element
  local build
  build=()
  # Evil quoting to survive an eval and to make sure that
  # this works even with variables containing IFS characters, if I'm
  # crazy enough to setopt shwordsplit.
  eval '
    foreach element in "$'"$1"'[@]"
    do
      if [[ -d "$element" ]]
      then
        build=("$build[@]" "$element")
      fi
    done
    '"$1"'=( "$build[@]" )
  '
}

rationalize_path "$@"

# vim: ft=zsh et tw=78 ts=2 sts=2 sw=2 cc=80
