#!/bin/zsh

# Convert a relative path to an absolute one
# From: https://unix.stackexchange.com/questions/24293
echo $(cd -- "$1" && pwd -P 2>/dev/null || pwd)

# vim: ft=zsh et tw=78 ts=2 sts=2 sw=2 cc=80
